<center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true" width="240" height="100" /></center>

**<center><h3>Recap: Python for Data Science Assignment Solution</h3></center>**

---
**<h4>Question 1:** Create a function that swap two numbers with their position.</h4>

---

- For example, you entered `a = 5` and `b = 6`.

- The value returned will be `a = 6` and `b = 5`.

<details>

**<summary>Hint:</summary>**

- There are two ways by which you can achieve this.

- Either you can take three variables or try out some maths operations.

</details>

In [ ]:
def swapValues(a=None, b=None):
  """Swapp two values using a third variable"""

  # Display original values
  print('Original a: {}'.format(a))
  print('Original b: {}'.format(b))
  print('-------------')

  # Swapping values using a third variable
  temp = a
  a = b
  b = temp

  # Display modified values  
  print('Modified a: {}'.format(a))
  print('Modified b: {}'.format(b))

In [ ]:
swapValues(a=5, b=6)

Original a: 5
Original b: 6
-------------
Modified a: 6
Modified b: 5

---
**<h4>Question 2:** Create a function that converts the datatype of a variable to a string type if it is not numeric.</h4>

---

- For example, you entered `num = 10` and its type is `int`.

- The value returned will be `num = 10` and its type will be `str`.

<details>

**<summary>Hint:</summary>**

- You must have learned about the typecasting in the python starter kit. Haven't you?

- You can either put chained conditions to identify the data type and then typecast it,

- Or directly convert the data type despite of its type.

</details>

In [ ]:
def convertType(num=None):
  """Typecast the datatype if it is not numeric"""

  # Dispaly original value and its type
  print('Original Value: {}'.format(num))
  print('Original Type: {}'.format(type(num)))
  print('-------------')

  # Perforing typecasting
  num = str(num)

  # Dispaly modifed value and its type
  print('Modified Value: {}'.format(num))
  print('Modified Type: {}'.format(type(num)))

In [ ]:
convertType(num=10)

Original Value: 10
Original Type: <class 'int'>
-------------
Modified Value: 10
Modified Type: <class 'str'>

---
**<h4>Question 3:** Create a function that calculates area of the triangle from user input.</h4>

---

- For example, you entered `base = 10` and `height = 3`.

- The value returned will be `area = 15`.

<details>

**<summary>Hint:</summary>**

- The formula to estimate area of triangle is $\large \frac{1}2 * base * height$

</details>

In [ ]:
def areaOfTriangle():
  """Estimates area of triangle"""

  # Taking user input
  base = float(input('Enter base value: '))
  height = float(input('Enter height value: '))

  # Calculate area of triangle
  area = 0.5 * base * height

  # Display estimated area
  print('Area of traingle: {}'.format(area))

In [ ]:
# Calling function to estimate area of triangle
areaOfTriangle()

Enter base value: 10
Enter height value: 3
Area of traingle: 15.0

---
**<h4>Question 4:** Create a function that displays largest number from the provided list.</h4>

---

- For example, there's a list as `[18, 12, 28, 16, 22, 29, 23, 26]`.

- The value returned will be `area = 29`.

<details>

**<summary>Hint:</summary>**

- You must have learned about the control flow in the python starter kit. Haven't you?

- There can be many ways to achieve this, but let's think in a simple logical way.

- You initialize a variable with any value present in the list. Let's say first value, list[0].

- Then iterate over each value present in the list and check if it's greater than the initialized value.

- If it's greater than the value you assign it back to the initialzed variable and return it.

</details>

In [ ]:
def maxValue(list_in):
  """Estimates maximum value present in the list"""

  # Initialize variable with a random value in the list
  max = list_in[0]

  # Iterate over the elements of the list
  for val in list_in:
    # Check if the current value in list is greater than initialized value
    # If it's greater then assign it back to the initialized value
    if (val > max):
      max = val

  # Display the max value
  print('Max value: {}'.format(max))

In [ ]:
maxValue(list_in=[18, 12, 28, 16, 22, 29, 23, 26])

Max value: 29

---
**<h4>Question 5:** Create a function that removes duplicate values from the provided list.</h4>

---

- For example, there's a list as `[10, 20, 30, 40, 50, 60, 70, 40, 80, 50, 40]`.

- The returned list will be `[70, 40, 10, 80, 50, 20, 60, 30]`.

<details>

**<summary>Hint:</summary>**

- You can typecast your list to a set type and then again typecast it to a list.

- You can also use control flow over the list with different python operators to achieve the objective.

</details>

In [ ]:
def removeDuplicates(list_in):
  """Removes duplicates if present in a list."""

  # Typecast list to set type
  to_set = set(list_in)

  # Typecast set to list again
  refined_list = list(to_set)

  # Display the refined list
  print('Refined List: {}'.format(refined_list))

In [ ]:
removeDuplicates(list_in=[10, 20, 30, 40, 50, 60, 70, 40, 80, 50, 40])

Refined List: [70, 40, 10, 80, 50, 20, 60, 30]

---
**<h4>Question 6:** Create a function that displays a sum of values present in a list.</h4>

---

- For example, there's a list as `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`.

- The returned sum will be `55`.

<details>

**<summary>Hint:</summary>**

- You must have learned about the control flow in the python starter kit. Haven't you?

- Initialize a variable with a zero value.

- Then iterate over the list along with the intialized value to get a sum. 

</details>

In [ ]:
def sumList(list_in):
  """Returns a sum of values present in a list"""

  # Initialized a variable with a zero value
  sum = 0

  # Iterate over the list with the intialized value
  for val in list_in:
    sum = sum + val

  # Display the final sum
  print('Sum of the list: {}'.format(sum))

In [ ]:
sumList(list_in=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Sum of the list: 55

---
**<h4>Question 7:** Create a function that reverse a provided string.</h4>

---

- For example, you passed a string such as `INSAID`.

- The returned string will be `DIASNI`.

<details>

**<summary>Hint:</summary>**

- There are several ways to achieving the defined objective.

- Either you can iterate over the characters of the string or use the string striding (mostly used).

</details>

In [ ]:
def stringReverse():
  """Returns a reversed string"""

  # Taking user input
  str_in = input('Enter a string: ')

  return str_in[::-1]

In [ ]:
# Display the reverse string
print('Reversed String: {}'.format(stringReverse()))

Enter a string: INSAID
Reversed String: DIASNI

---
**<h4>Question 8:** Create a function that returns a combination of two tuples.</h4>

---

- For example, you passed two tuples such as `(0, 1, 2, 3)` and `('python', 'code')`.

- The returned tuple will be `(0, 1, 2, 3, 'python', 'code')`.

<details>

**<summary>Hint:</summary>**

- Why don't you try out the simple mathematical operation such as addition.

</details>

In [ ]:
def concatTuple(tup1=None, tup2=None):
  """Returns a concatenation of two tuples"""
  return tup1+tup2

In [ ]:
tuple1 = (0, 1, 2, 3)
tuple2 = ('python', 'code')

# Display the concatenation of tuples
print('Concatenated Tuple: {}'.format(concatTuple(tup1=tuple1, tup2=tuple2)))

Concatenated Tuple: (0, 1, 2, 3, 'python', 'code')

---
**<h4>Question 9:** Create a function that returns an indicator of whether a provided key already exists in a dictionary.</h4>

---

- For example, there's a dictionary such as `{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}`.

- You passed a value to the function such as `3`, then a returned value will be `True`.

- Let's say you passed a value to the function such as `8`, then a returned value will be `False`.

<details>

**<summary>Hint:</summary>**

- You must have learned about the control flow and operators in the python starter kit. Haven't you?

- You can get the desired result using simple IF-ELSE operation.

</details>

In [ ]:
def isKeyPresent(dict_in=None, key=None):
  if key in dict_in:
    return True
  else:
    return False

In [ ]:
dict_in = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}

# Display the indicator
print('Returned Indicator: {}'.format(isKeyPresent(dict_in=dict_in, key=4)))

Returned Indicator: True

---
**<h4>Question 10:** Create a function that returns a combination of two python dictionary.</h4>

---

- For example, there's are two dictionaries such as `{'a': 100, 'b': 200}` and `{'x': 300, 'y': 200}`.

- The returned dictionary will be `{'a': 100, 'b': 200, 'x': 300, 'y': 200}`.

<details>

**<summary>Hint:</summary>**

- Initialize a variable with empty dictionary or using dict() method.

- Update the newly initialized dictionary with the first dictionary using .update() method.

- Then again update the newly initialized dictionary with the second dictionary using .update() method.

</details>

In [ ]:
def combineDict(dict1=None, dict2=None):
  """Returns a concatenation of two dictionaries"""

  # Intialize a variable as dictionary
  final_dict = dict()

  # Update the intialized dictionary with dictionary 1
  final_dict.update(dict1)

  # Update the intialized dictionary with dictionary 2
  final_dict.update(dict2)

  return final_dict

In [ ]:
d1 = {'a': 100, 'b': 200}
d2 = {'x': 300, 'y': 200}

# Display the final dictionary
print('Final Dictionary: {}'.format(combineDict(dict1=d1, dict2=d2)))

Final Dictionary: {'a': 100, 'b': 200, 'x': 300, 'y': 200}

---
**<h4>Question 11:** Create a function that returns a factorial of a number.</h4>

---

- For example, you passed `val = 5`.

- The returned value will be `120`.

- Underlying working is as shown: `1 * 2 * 3 * 4 * 5 = 120`.

<details>

**<summary>Hint:</summary>**

- Initialize factorial varialble with 1.

- If the number is negative display message that factorial of a negative number doesn't exist.

- Else if the number is zero return the initialized value.

- Else return the factorial value over the specified value in the function.

</details>

In [ ]:
def factorial():

  # Take a user input
  num = int(input('Enter a value: '))

  # Initialize variable with 1
  fact = 1
  
  # If the number is negative, display a message
  if num < 0:
    print("Sorry, factorial does not exist for negative numbers")
  
  # If the number is zero, then return 1
  elif num == 0:
   return fact
   
  # Else iterate over the specified range of number
  else:
   for i in range(1, num + 1):
     fact = fact * i

  return fact

In [ ]:
# Display the fictorial value
print('Factorial: {}'.format(factorial()))

Enter a value: 5
Factorial: 120